export const announcementItems = [
  "FREE SHIPPING ABOVE RS. 999",
  "LAB TESTED AND 100% AUTHENTIC",
  "4.5+ RATED BY 10,000+ CUSTOMERS",
  "2% OFF ON PREPAID ORDERS",
];

export const categories = [
  {
    slug: "whey-protein",
    name: "Whey Protein",
    tag: "WP",
    description: "Daily recovery support for lean muscle goals.",
  },
  {
    slug: "creatine",
    name: "Creatine",
    tag: "CR",
    description: "Strength output and faster training recovery.",
  },
  {
    slug: "mass-gainers",
    name: "Mass Gainers",
    tag: "MG",
    description: "Calorie-dense blends for hard gainers.",
  },
  {
    slug: "vitamins",
    name: "Vitamins",
    tag: "VT",
    description: "Foundational health and performance support.",
  },
  {
    slug: "pre-workout",
    name: "Pre-Workout",
    tag: "PW",
    description: "Focus, pump, and energy before training.",
  },
  {
    slug: "amino-acids",
    name: "Amino Acids",
    tag: "AA",
    description: "Hydration and intra-workout recovery blends.",
  },
];

export const goals = [
  {
    slug: "muscle-gain",
    title: "Muscle Gain",
    copy: "High-protein formulas for faster repair and size-focused phases.",
    cta: "See Products",
  },
  {
    slug: "weight-loss",
    title: "Weight Loss",
    copy: "Lean nutrition and low-sugar support to cut without compromise.",
    cta: "See Products",
  },
  {
    slug: "endurance",
    title: "Endurance and Stamina",
    copy: "Performance-first products for longer sessions and cleaner output.",
    cta: "See Products",
  },
];

export const brands = [
  "MuscleBlaze",
  "Optimum Nutrition",
  "AS-IT-IS",
  "MyProtein",
  "Dymatize",
  "MuscleTech",
  "GNC",
  "BSN",
];

export const reviews = [
  {
    initials: "RK",
    name: "Rahul K.",
    rating: "5.0",
    text: "Biozyme has been easy to digest and the order came exactly when promised.",
    product: "Biozyme Performance Whey",
  },
  {
    initials: "PS",
    name: "Priya S.",
    rating: "5.0",
    text: "Creatine mixes cleanly, pricing feels fair, and I trust the verified sourcing angle.",
    product: "Micronized Creatine",
  },
  {
    initials: "AM",
    name: "Arjun M.",
    rating: "4.5",
    text: "Customer support followed up fast and the packaging felt authentic and secure.",
    product: "Gold Standard Whey",
  },
];

export const trustPoints = [
  {
    tag: "LT",
    title: "Lab Tested",
    copy: "Every featured product is positioned for verified quality.",
  },
  {
    tag: "FS",
    title: "Free Shipping",
    copy: "Orders above Rs. 999 are delivered with zero shipping fees.",
  },
  {
    tag: "ER",
    title: "Easy Returns",
    copy: "Simple support-led returns flow for eligible orders.",
  },
  {
    tag: "SP",
    title: "Secure Payments",
    copy: "Frontend is ready for UPI, cards, net banking, and COD flows.",
  },
];

export const authenticityPoints = [
  "Only verified brands",
  "Lab reports ready to attach product-by-product",
  "Tamper-aware packaging communication",
  "Built for prepaid and COD checkout flows",
];

export const products = [
  {
    id: "bn-001",
    slug: "biozyme-whey",
    brand: "MuscleBlaze",
    name: "Biozyme Performance Whey Protein",
    shortName: "Biozyme Whey",
    category: "whey-protein",
    goal: "muscle-gain",
    color: "orange",
    image: "assets/products/biozyme-whey.webp",
    heroImage: "assets/hero/biozyme-whey-hero.webp",
    ratingAverage: 4.2,
    ratingCount: 1240,
    badges: ["LAB TESTED", "BEST SELLER"],
    description:
      "Fast-digesting whey with enzyme support, athlete-friendly macros, and everyday recovery focus.",
    highlights: [
      "27g protein per serving",
      "Zero filler positioning",
      "Best for post-workout recovery",
    ],
    nutritionFacts: [
      "Protein: 27g",
      "BCAA: 5.8g",
      "Calories: 129",
      "Added sugar: 0g",
    ],
    variants: [
      {
        id: "biozyme-whey-1kg-rich-chocolate",
        flavour: "Rich Chocolate",
        size: "1kg",
        price: 2499,
        mrp: 3199,
        stock: 50,
      },
      {
        id: "biozyme-whey-2kg-rich-chocolate",
        flavour: "Rich Chocolate",
        size: "2kg",
        price: 4399,
        mrp: 5599,
        stock: 36,
      },
      {
        id: "biozyme-whey-1kg-cafe-mocha",
        flavour: "Cafe Mocha",
        size: "1kg",
        price: 2599,
        mrp: 3199,
        stock: 21,
      },
    ],
    labReportUrl: "#",
  },
  {
    id: "bn-002",
    slug: "gold-standard",
    brand: "Optimum Nutrition",
    name: "Gold Standard 100% Whey",
    shortName: "Gold Standard Whey",
    category: "whey-protein",
    goal: "muscle-gain",
    color: "dark",
    image: "assets/products/gold-standard.webp",
    heroImage: "assets/hero/biozyme-whey-hero.webp",
    ratingAverage: 4.5,
    ratingCount: 3820,
    badges: ["LAB TESTED", "NEW"],
    description:
      "A premium whey isolate-led blend for serious training blocks and consistent recovery.",
    highlights: [
      "Trusted international formula",
      "Lean macro profile",
      "Reliable all-day protein option",
    ],
    nutritionFacts: [
      "Protein: 24g",
      "Calories: 120",
      "Sugar: 1g",
      "Glutamine support included",
    ],
    variants: [
      {
        id: "gold-standard-2lb-double-rich-chocolate",
        flavour: "Double Rich Chocolate",
        size: "2lb",
        price: 3499,
        mrp: 4299,
        stock: 18,
      },
      {
        id: "gold-standard-5lb-double-rich-chocolate",
        flavour: "Double Rich Chocolate",
        size: "5lb",
        price: 7799,
        mrp: 9199,
        stock: 9,
      },
    ],
    labReportUrl: "#",
  },
  {
    id: "bn-003",
    slug: "creatine-asitis",
    brand: "AS-IT-IS",
    name: "Micronized Creatine Monohydrate",
    shortName: "Micronized Creatine",
    category: "creatine",
    goal: "endurance",
    color: "blue",
    image: "assets/products/creatine-asitis.jpg",
    heroImage: "assets/hero/creatine-hero.jpg",
    ratingAverage: 4.4,
    ratingCount: 5600,
    badges: ["LAB TESTED", "BEST SELLER"],
    description:
      "Micronized creatine built for strength cycles, muscle fullness, and repeatable daily use.",
    highlights: [
      "Unflavoured daily-use format",
      "Great for strength blocks",
      "Easy stack with whey and pre-workout",
    ],
    nutritionFacts: [
      "Creatine monohydrate: 3g",
      "Sugar: 0g",
      "Calories: 0",
      "No stimulants",
    ],
    variants: [
      {
        id: "creatine-asitis-250g-unflavoured",
        flavour: "Unflavoured",
        size: "250g",
        price: 699,
        mrp: 999,
        stock: 72,
      },
      {
        id: "creatine-asitis-500g-unflavoured",
        flavour: "Unflavoured",
        size: "500g",
        price: 1299,
        mrp: 1699,
        stock: 41,
      },
    ],
    labReportUrl: "#",
  },
  {
    id: "bn-004",
    slug: "mass-gainer-xxl",
    brand: "MuscleBlaze",
    name: "Super Mass Gainer XXL",
    shortName: "Mass Gainer XXL",
    category: "mass-gainers",
    goal: "muscle-gain",
    color: "orange",
    image: "assets/products/mass-gainer-xxl.jpg",
    heroImage: "assets/hero/preworkout-hero.jpg",
    ratingAverage: 4.0,
    ratingCount: 890,
    badges: ["SALE"],
    description:
      "High-calorie protein-carb blend designed for bulking phases and calorie surplus support.",
    highlights: [
      "Large scoop calorie support",
      "Protein plus carbohydrate blend",
      "Useful for hard-gainer meal gaps",
    ],
    nutritionFacts: [
      "Protein: 30g",
      "Calories: 410",
      "Carbs: 62g",
      "Fiber support included",
    ],
    variants: [
      {
        id: "mass-gainer-xxl-1kg-chocolate",
        flavour: "Chocolate",
        size: "1kg",
        price: 1799,
        mrp: 2499,
        stock: 14,
      },
      {
        id: "mass-gainer-xxl-3kg-chocolate",
        flavour: "Chocolate",
        size: "3kg",
        price: 3999,
        mrp: 5099,
        stock: 8,
      },
    ],
    labReportUrl: "#",
  },
  {
    id: "bn-005",
    slug: "pre-workout-edge",
    brand: "MuscleTech",
    name: "Shatter Elite Pre-Workout",
    shortName: "Shatter Elite",
    category: "pre-workout",
    goal: "endurance",
    color: "red",
    image: "assets/products/pre-workout.png",
    heroImage: "assets/hero/preworkout-hero.jpg",
    ratingAverage: 4.3,
    ratingCount: 640,
    badges: ["NEW"],
    description:
      "Performance pre-workout for focus, drive, and pump before high-output sessions.",
    highlights: [
      "High-energy pre-lift support",
      "Made for focus-driven sessions",
      "Pairs well with creatine",
    ],
    nutritionFacts: [
      "Caffeine: 200mg",
      "Citrulline blend included",
      "Beta-alanine support",
      "Sugar free positioning",
    ],
    variants: [
      {
        id: "pre-workout-edge-30-servings-fruit-punch",
        flavour: "Fruit Punch",
        size: "30 servings",
        price: 1699,
        mrp: 2199,
        stock: 29,
      },
    ],
    labReportUrl: "#",
  },
  {
    id: "bn-006",
    slug: "vitamin-d3",
    brand: "GNC",
    name: "Vitamin D3 Daily Support",
    shortName: "Vitamin D3",
    category: "vitamins",
    goal: "weight-loss",
    color: "yellow",
    image: "assets/products/vitamin-d3.webp",
    heroImage: "assets/hero/creatine-hero.jpg",
    ratingAverage: 4.6,
    ratingCount: 410,
    badges: ["LAB TESTED"],
    description:
      "Simple everyday vitamin support to complement training, energy, and general health.",
    highlights: [
      "Daily wellness support",
      "Easy once-a-day routine",
      "Useful alongside protein stacks",
    ],
    nutritionFacts: [
      "Vitamin D3: 2000 IU",
      "60 tablets",
      "No added sugar",
      "Balanced daily support",
    ],
    variants: [
      {
        id: "vitamin-d3-60-tablets",
        flavour: "Unflavoured",
        size: "60 tablets",
        price: 799,
        mrp: 999,
        stock: 53,
      },
    ],
    labReportUrl: "#",
  },
  {
    id: "bn-007",
    slug: "bcaa-hydra",
    brand: "MyProtein",
    name: "BCAA Hydra Recovery Blend",
    shortName: "BCAA Hydra",
    category: "amino-acids",
    goal: "endurance",
    color: "green",
    image: "assets/products/bcaa.webp",
    heroImage: "assets/hero/preworkout-hero.jpg",
    ratingAverage: 4.1,
    ratingCount: 300,
    badges: ["SALE"],
    description:
      "Hydration-minded BCAA blend for intra-workout support and longer training days.",
    highlights: [
      "Hydration-first amino format",
      "Great for long sessions",
      "Useful during cutting phases",
    ],
    nutritionFacts: [
      "BCAA ratio: 2:1:1",
      "Electrolyte support",
      "Calories: 18",
      "Low sugar profile",
    ],
    variants: [
      {
        id: "bcaa-hydra-30-servings-blue-raspberry",
        flavour: "Blue Raspberry",
        size: "30 servings",
        price: 1499,
        mrp: 1899,
        stock: 22,
      },
    ],
    labReportUrl: "#",
  },
  {
    id: "bn-008",
    slug: "casein-night-fuel",
    brand: "Dymatize",
    name: "Elite Casein Night Fuel",
    shortName: "Elite Casein",
    category: "whey-protein",
    goal: "muscle-gain",
    color: "dark",
    image: "assets/products/casein.webp",
    heroImage: "assets/hero/biozyme-whey-hero.webp",
    ratingAverage: 4.3,
    ratingCount: 210,
    badges: ["LAB TESTED"],
    description:
      "Slow-digesting protein intended for evening use and longer recovery windows.",
    highlights: [
      "Slow release recovery support",
      "Good for nighttime nutrition",
      "Complements whey-based stacks",
    ],
    nutritionFacts: [
      "Protein: 25g",
      "Calories: 130",
      "Carbs: 3g",
      "Low sugar blend",
    ],
    variants: [
      {
        id: "casein-night-fuel-1kg-vanilla",
        flavour: "Vanilla",
        size: "1kg",
        price: 2899,
        mrp: 3499,
        stock: 12,
      },
    ],
    labReportUrl: "#",
  },
];

export const heroSlides = [
  {
    eyebrow: "New Arrivals · Premium Range",
    title: "Pure Whey Protein",
    subtitle: "27g protein · zero filler positioning · lab tested",
    cta: "Shop Now",
    productSlug: "biozyme-whey",
    image: "assets/hero/biozyme-whey-hero.webp",
  },
  {
    eyebrow: "Strength Essentials",
    title: "Micronized Creatine",
    subtitle: "Daily power output support with clean mixability",
    cta: "Explore Creatine",
    productSlug: "creatine-asitis",
    image: "assets/hero/creatine-hero.jpg",
  },
  {
    eyebrow: "Session Energy",
    title: "Pre-Workout Edge",
    subtitle: "Focus, pump, and drive before your toughest sets",
    cta: "See Pre-Workout",
    productSlug: "pre-workout-edge",
    image: "assets/hero/preworkout-hero.jpg",
  },
];
